apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhtap-go-repo
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rhtap-go-repo/overlays/development
    repoURL: https://github.com/prietyc123-qe-org/rhtap-go-repo-gitops
    targetRevision: main
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
