apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-go-repo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-go-repo 
  name: rhtap-go-repo
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhtap-go-repo 
